/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import interfas.Animacion;

/**
 *
 * @author ruben
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    
    Animacion anim = new Animacion();
    String[] Paneles = {"No hay nada aqui", "Libro Diario","Libro Mayor","Balance de Comprobacion","Estado de Resultados","Balance General","No hay nada aqui"};
    
    String PanelActual;
    int Contador;    
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    
        
    /*------------Todo este codigo ira en una funcion-------------*/    
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnCerrar, "src/Imagenes/multiply.png");
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnMinimizar, "src/Imagenes/subtraction.png");   
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnAnterior, "src/Imagenes/left-arrow.png");
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnSiguiente, "src/Imagenes/right-arrow.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnAgregar, "src/Imagenes/plus.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnEditar, "src/Imagenes/equal.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnEliminar, "src/Imagenes/eliminar.png");
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnModificar, "src/Imagenes/writing.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnAjuste, "src/Imagenes/calculator.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnActualizarMyr, "src/Imagenes/update.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnActualizarComp, "src/Imagenes/update.png");
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnActualizarEstRes, "src/Imagenes/update.png"); 
    rsscalelabel.RSScaleLabel.setScaleLabel(this.btnActualizarBG, "src/Imagenes/update.png"); 
    
    PanelActual = Paneles[1];
    Contador = 1;
    btnAnterior.setToolTipText(Paneles[Contador-1]);
    btnSiguiente.setToolTipText(Paneles[Contador+1]);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNav = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JLabel();
        AbrirNav = new javax.swing.JLabel();
        PanelLibroDiario = new javax.swing.JPanel();
        PanelEditPartida = new javax.swing.JPanel();
        btnAjuste = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        AbrirNav1 = new javax.swing.JLabel();
        AbrirNav3 = new javax.swing.JLabel();
        AbrirNav4 = new javax.swing.JLabel();
        AbrirNav5 = new javax.swing.JLabel();
        AbrirNav6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPeriodo = new javax.swing.JLabel();
        AbrirNav2 = new javax.swing.JLabel();
        PanelLibroMayor = new javax.swing.JPanel();
        AbrirNav7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMayor = new javax.swing.JTable();
        AbrirNav8 = new javax.swing.JLabel();
        btnActualizarMyr = new javax.swing.JLabel();
        PanelBalanceComprobacion = new javax.swing.JPanel();
        AbrirNav9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaMayor1 = new javax.swing.JTable();
        AbrirNav10 = new javax.swing.JLabel();
        btnActualizarComp = new javax.swing.JLabel();
        AbrirNav11 = new javax.swing.JLabel();
        txtHaberComprobacion = new javax.swing.JTextField();
        txtDebeComprobacion1 = new javax.swing.JTextField();
        PanelEstadoResultados = new javax.swing.JPanel();
        AbrirNav12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblEstadoRes = new javax.swing.JTable();
        AbrirNav13 = new javax.swing.JLabel();
        btnActualizarEstRes = new javax.swing.JLabel();
        PanelBalanceGeneral = new javax.swing.JPanel();
        lblBG = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPasivosBG = new javax.swing.JTable();
        EmpresaBG = new javax.swing.JLabel();
        btnActualizarBG = new javax.swing.JLabel();
        lblTOTALESBG = new javax.swing.JLabel();
        txtBG1 = new javax.swing.JTextField();
        txtActivoBG = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblActivosBG1 = new javax.swing.JTable();
        txtPasivoBG = new javax.swing.JTextField();
        txtBG2 = new javax.swing.JTextField();
        txtBG3 = new javax.swing.JTextField();
        PanelEncabezado = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        lblPanelActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(81, 110, 128));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(81, 110, 128));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(920, 570));
        setResizable(false);
        setSize(new java.awt.Dimension(920, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNavMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNavMouseExited(evt);
            }
        });

        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
        });

        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnteriorMouseClicked(evt);
            }
        });

        AbrirNav.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav.setText("Navegacion");
        AbrirNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AbrirNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbrirNavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelNavLayout = new javax.swing.GroupLayout(PanelNav);
        PanelNav.setLayout(PanelNavLayout);
        PanelNavLayout.setHorizontalGroup(
            PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavLayout.createSequentialGroup()
                .addGroup(PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNavLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNavLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(AbrirNav)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelNavLayout.setVerticalGroup(
            PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PanelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(AbrirNav, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PanelNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -100, 180, -1));

        PanelLibroDiario.setBackground(new java.awt.Color(81, 110, 128));
        PanelLibroDiario.setPreferredSize(new java.awt.Dimension(920, 540));
        PanelLibroDiario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEditPartida.setBackground(new java.awt.Color(102, 137, 203));
        PanelEditPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEditPartidaMouseExited(evt);
            }
        });

        btnAjuste.setBackground(new java.awt.Color(241, 237, 225));
        btnAjuste.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAjuste.setForeground(new java.awt.Color(255, 255, 255));
        btnAjuste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjuste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjuste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjusteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        AbrirNav1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AbrirNav1.setText("Agregar Partida");
        AbrirNav1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AbrirNav3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AbrirNav3.setText("Eliminar Partida");
        AbrirNav3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AbrirNav4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav4.setText("Menù");
        AbrirNav4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AbrirNav5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AbrirNav5.setText("Modificar Partiida");
        AbrirNav5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AbrirNav6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AbrirNav6.setText("Ajuste de IVA");
        AbrirNav6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PanelEditPartidaLayout = new javax.swing.GroupLayout(PanelEditPartida);
        PanelEditPartida.setLayout(PanelEditPartidaLayout);
        PanelEditPartidaLayout.setHorizontalGroup(
            PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditPartidaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                        .addComponent(AbrirNav1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                        .addComponent(AbrirNav5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                        .addComponent(AbrirNav3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                        .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                                .addComponent(AbrirNav6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                            .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                                .addComponent(AbrirNav4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjuste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        PanelEditPartidaLayout.setVerticalGroup(
            PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditPartidaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirNav4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjuste, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirNav6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirNav1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirNav3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEditPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirNav5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        PanelLibroDiario.add(PanelEditPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 90, 280, 330));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PanelLibroDiario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 750, 360));

        lblPeriodo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeriodo.setText("Libro Diario, del 1 de enero al 31 de diciembre de 2018");
        lblPeriodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelLibroDiario.add(lblPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 750, -1));

        AbrirNav2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav2.setText("Agro Ferreteria San Francisco");
        AbrirNav2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelLibroDiario.add(AbrirNav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 750, -1));

        getContentPane().add(PanelLibroDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        PanelLibroMayor.setBackground(new java.awt.Color(105, 171, 165));
        PanelLibroMayor.setPreferredSize(new java.awt.Dimension(920, 540));
        PanelLibroMayor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbrirNav7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav7.setText("Libro Mayor del 1 de enero al 31 de diciembre de 2018");
        AbrirNav7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLibroMayor.add(AbrirNav7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 750, -1));

        TablaMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaMayor);

        PanelLibroMayor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 750, 340));

        AbrirNav8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav8.setText("Agro Ferreteria San Francisco");
        AbrirNav8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLibroMayor.add(AbrirNav8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 750, -1));

        btnActualizarMyr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarMyr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMyrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMyrbtnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMyrbtnEditarMouseExited(evt);
            }
        });
        PanelLibroMayor.add(btnActualizarMyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 50, 50));

        getContentPane().add(PanelLibroMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, -1, 530));

        PanelBalanceComprobacion.setBackground(new java.awt.Color(122, 153, 199));
        PanelBalanceComprobacion.setPreferredSize(new java.awt.Dimension(920, 540));
        PanelBalanceComprobacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbrirNav9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav9.setText("Balance de Comprobacion del 1 de enero al 31 de diciembre de 2018");
        AbrirNav9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelBalanceComprobacion.add(AbrirNav9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 750, -1));

        TablaMayor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaMayor1);

        PanelBalanceComprobacion.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 750, 370));

        AbrirNav10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav10.setText("Agro Ferreteria San Francisco");
        AbrirNav10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelBalanceComprobacion.add(AbrirNav10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 750, -1));

        btnActualizarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarCompbtnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarCompbtnEditarMouseExited(evt);
            }
        });
        PanelBalanceComprobacion.add(btnActualizarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 50, 50));

        AbrirNav11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav11.setText("TOTALES");
        AbrirNav11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBalanceComprobacion.add(AbrirNav11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 100, -1));

        txtHaberComprobacion.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceComprobacion.add(txtHaberComprobacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 160, 20));

        txtDebeComprobacion1.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceComprobacion.add(txtDebeComprobacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 160, 20));

        getContentPane().add(PanelBalanceComprobacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 50, -1, 530));

        PanelEstadoResultados.setBackground(new java.awt.Color(198, 231, 246));
        PanelEstadoResultados.setPreferredSize(new java.awt.Dimension(920, 540));
        PanelEstadoResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbrirNav12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav12.setText("Estado de Resultados del 1 de enero al 31 de diciembre de 2018");
        AbrirNav12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelEstadoResultados.add(AbrirNav12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 750, -1));

        tblEstadoRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblEstadoRes);

        PanelEstadoResultados.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 750, 370));

        AbrirNav13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        AbrirNav13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AbrirNav13.setText("Agro Ferreteria San Francisco");
        AbrirNav13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelEstadoResultados.add(AbrirNav13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 750, -1));

        btnActualizarEstRes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarEstRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarEstResMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarEstResbtnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarEstResbtnEditarMouseExited(evt);
            }
        });
        PanelEstadoResultados.add(btnActualizarEstRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 50, 50));

        getContentPane().add(PanelEstadoResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(2760, 50, -1, 530));

        PanelBalanceGeneral.setBackground(new java.awt.Color(201, 210, 209));
        PanelBalanceGeneral.setPreferredSize(new java.awt.Dimension(920, 540));
        PanelBalanceGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBG.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBG.setText("Balance General del 1 de enero al 31 de diciembre de 2018");
        lblBG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelBalanceGeneral.add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 750, -1));

        tblPasivosBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(tblPasivosBG);

        PanelBalanceGeneral.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 360, 370));

        EmpresaBG.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        EmpresaBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpresaBG.setText("Agro Ferreteria San Francisco");
        EmpresaBG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelBalanceGeneral.add(EmpresaBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 750, -1));

        btnActualizarBG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarBGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarBGbtnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarBGbtnEditarMouseExited(evt);
            }
        });
        PanelBalanceGeneral.add(btnActualizarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 50, 50));

        lblTOTALESBG.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTOTALESBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTOTALESBG.setText("TOTALES");
        lblTOTALESBG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBalanceGeneral.add(lblTOTALESBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 100, -1));

        txtBG1.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceGeneral.add(txtBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 70, 20));

        txtActivoBG.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceGeneral.add(txtActivoBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 160, 20));

        tblActivosBG1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane6.setViewportView(tblActivosBG1);

        PanelBalanceGeneral.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 360, 370));

        txtPasivoBG.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceGeneral.add(txtPasivoBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 160, 20));

        txtBG2.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceGeneral.add(txtBG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 70, 20));

        txtBG3.setBackground(new java.awt.Color(241, 237, 225));
        PanelBalanceGeneral.add(txtBG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 70, 20));

        getContentPane().add(PanelBalanceGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(3680, 50, -1, 530));

        PanelEncabezado.setBackground(new java.awt.Color(241, 237, 225));

        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });

        lblPanelActual.setBackground(new java.awt.Color(0, 27, 27));
        lblPanelActual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPanelActual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPanelActual.setText("Bienvenido al sistema");
        lblPanelActual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPanelActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPanelActualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelEncabezadoLayout = new javax.swing.GroupLayout(PanelEncabezado);
        PanelEncabezado.setLayout(PanelEncabezadoLayout);
        PanelEncabezadoLayout.setHorizontalGroup(
            PanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPanelActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelEncabezadoLayout.setVerticalGroup(
            PanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPanelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
    
    System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
     
        this.setExtendedState(ICONIFIED);
     
    }//GEN-LAST:event_btnMinimizarMouseClicked

    
    
    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteMouseClicked
    
    if(PanelBalanceGeneral.getX() != 0){
        
    Contador++;
    Avanzar();
    
    if(PanelBalanceGeneral.getX() == 0){PanelActual = Paneles[1];}
    
    if(Contador-1 >= 0){
              
    btnAnterior.setToolTipText(Paneles[Contador-1]);
    btnSiguiente.setToolTipText(Paneles[Contador+1]);
    
    }
    
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnteriorMouseClicked
    
    if(PanelLibroDiario.getX() != 0){
    
    Contador--;    
    Retroceder();
      
    if(PanelLibroDiario.getX() == 0){PanelActual = Paneles[0];}
    
    if(Contador+1 < Paneles.length){
      
    btnAnterior.setToolTipText(Paneles[Contador-1]);
    btnSiguiente.setToolTipText(Paneles[Contador+1]);
    }
    
    }

// TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorMouseClicked

    private void PanelNavMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNavMouseEntered
    
    anim.jPanelYDown(-100, -80, 2, 1, PanelNav);

    }//GEN-LAST:event_PanelNavMouseEntered

    private void PanelNavMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNavMouseExited
        
    anim.jPanelYUp(-80, -100, 2, 1, PanelNav);

    }//GEN-LAST:event_PanelNavMouseExited

    private void AbrirNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbrirNavMouseClicked
    
    anim.jPanelYDown(-80, 0, 2, 1, PanelNav);
    
    anim.jPanelYUp(0, -100, 2, 1, PanelNav);

    }//GEN-LAST:event_AbrirNavMouseClicked

    
  /* botones de chepe */  
    
    
    private void btnAjusteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjusteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjusteMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked


/* metodos a borrar    
    
    private void PanelEditPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditPartidaMouseEntered
      
    //anim.jPanelXRight(-200, -190, 2, 1, PanelEditPartida);    
        
// TODO add your handling code here:
    }//GEN-LAST:event_PanelEditPartidaMouseEntered

    private void PanelEditPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditPartidaMouseExited
    
    //anim.jPanelXLeft(-190, -200, 2, 1, PanelEditPartida); 
// TODO add your handling code here:
    }//GEN-LAST:event_PanelEditPartidaMouseExited

 Fin de metodos */   
    
    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseClicked

    
    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
       
   anim.jPanelXRight(-200, 0, 2, 1, PanelEditPartida);   
   anim.jPanelXLeft(0, -200, 2, 1, PanelEditPartida);
   
   
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseClicked

    
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseClicked

    
    
    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
    
        
// borrar
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // borrar
    }//GEN-LAST:event_btnEditarMouseExited
    
    
    private void btnActualizarMyrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMyrMouseClicked
        // btn actualizar del libro mayor
    }//GEN-LAST:event_btnActualizarMyrMouseClicked

    private void btnActualizarMyrbtnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMyrbtnEditarMouseEntered
        // borrar
    }//GEN-LAST:event_btnActualizarMyrbtnEditarMouseEntered

    private void btnActualizarMyrbtnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMyrbtnEditarMouseExited
        // borrar
    }//GEN-LAST:event_btnActualizarMyrbtnEditarMouseExited

    private void lblPanelActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPanelActualMouseClicked
        // borrar
    }//GEN-LAST:event_lblPanelActualMouseClicked

    private void btnActualizarCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCompMouseClicked
        // actualizar de comprobacion
    }//GEN-LAST:event_btnActualizarCompMouseClicked

    private void btnActualizarCompbtnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCompbtnEditarMouseEntered
        // borrar
    }//GEN-LAST:event_btnActualizarCompbtnEditarMouseEntered

    private void btnActualizarCompbtnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarCompbtnEditarMouseExited
        // borrar
    }//GEN-LAST:event_btnActualizarCompbtnEditarMouseExited

    private void btnActualizarEstResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEstResMouseClicked
        // actualizar estado de resultados
    }//GEN-LAST:event_btnActualizarEstResMouseClicked

    private void btnActualizarEstResbtnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEstResbtnEditarMouseEntered
        //  borrar
    }//GEN-LAST:event_btnActualizarEstResbtnEditarMouseEntered

    private void btnActualizarEstResbtnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEstResbtnEditarMouseExited
        //  borrar
    }//GEN-LAST:event_btnActualizarEstResbtnEditarMouseExited

    private void btnActualizarBGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarBGMouseClicked
        // actualizar balance general
    }//GEN-LAST:event_btnActualizarBGMouseClicked

    private void btnActualizarBGbtnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarBGbtnEditarMouseEntered
        //  borrar
    }//GEN-LAST:event_btnActualizarBGbtnEditarMouseEntered

    private void btnActualizarBGbtnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarBGbtnEditarMouseExited
        //  borrar
    }//GEN-LAST:event_btnActualizarBGbtnEditarMouseExited
    
    
    public void Retroceder(){
    
    anim.jPanelXRight(PanelLibroMayor.getX(),PanelLibroMayor.getX()+920, 1, 5, PanelLibroMayor);
    anim.jPanelXRight(PanelLibroDiario.getX(), PanelLibroDiario.getX()+920, 1, 5, PanelLibroDiario);
    anim.jPanelXRight(PanelBalanceComprobacion.getX(),PanelBalanceComprobacion.getX()+920, 1, 5, PanelBalanceComprobacion);
    anim.jPanelXRight(PanelEstadoResultados.getX(), PanelEstadoResultados.getX()+920, 1, 5, PanelEstadoResultados);
    anim.jPanelXRight(PanelBalanceGeneral.getX(),PanelBalanceGeneral.getX()+920, 1, 5, PanelBalanceGeneral);
    
    }
    
    public void Avanzar(){
    
    anim.jPanelXLeft(PanelLibroMayor.getX(),PanelLibroMayor.getX()-920, 1, 5, PanelLibroMayor);
    anim.jPanelXLeft(PanelLibroDiario.getX(), PanelLibroDiario.getX()-920, 1, 5, PanelLibroDiario);
    anim.jPanelXLeft(PanelBalanceComprobacion.getX(),PanelBalanceComprobacion.getX()-920, 1, 5, PanelBalanceComprobacion);
    anim.jPanelXLeft(PanelEstadoResultados.getX(), PanelEstadoResultados.getX()-920, 1, 5, PanelEstadoResultados);
    anim.jPanelXLeft(PanelBalanceGeneral.getX(),PanelBalanceGeneral.getX()-920, 1, 5, PanelBalanceGeneral);
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AbrirNav;
    private javax.swing.JLabel AbrirNav1;
    private javax.swing.JLabel AbrirNav10;
    private javax.swing.JLabel AbrirNav11;
    private javax.swing.JLabel AbrirNav12;
    private javax.swing.JLabel AbrirNav13;
    private javax.swing.JLabel AbrirNav2;
    private javax.swing.JLabel AbrirNav3;
    private javax.swing.JLabel AbrirNav4;
    private javax.swing.JLabel AbrirNav5;
    private javax.swing.JLabel AbrirNav6;
    private javax.swing.JLabel AbrirNav7;
    private javax.swing.JLabel AbrirNav8;
    private javax.swing.JLabel AbrirNav9;
    private javax.swing.JLabel EmpresaBG;
    private javax.swing.JPanel PanelBalanceComprobacion;
    private javax.swing.JPanel PanelBalanceGeneral;
    private javax.swing.JPanel PanelEditPartida;
    private javax.swing.JPanel PanelEncabezado;
    private javax.swing.JPanel PanelEstadoResultados;
    private javax.swing.JPanel PanelLibroDiario;
    private javax.swing.JPanel PanelLibroMayor;
    private javax.swing.JPanel PanelNav;
    private javax.swing.JTable TablaMayor;
    private javax.swing.JTable TablaMayor1;
    private javax.swing.JLabel btnActualizarBG;
    private javax.swing.JLabel btnActualizarComp;
    private javax.swing.JLabel btnActualizarEstRes;
    private javax.swing.JLabel btnActualizarMyr;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnAjuste;
    private javax.swing.JLabel btnAnterior;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblPanelActual;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblTOTALESBG;
    private javax.swing.JTable tblActivosBG1;
    private javax.swing.JTable tblEstadoRes;
    private javax.swing.JTable tblPasivosBG;
    private javax.swing.JTextField txtActivoBG;
    private javax.swing.JTextField txtBG1;
    private javax.swing.JTextField txtBG2;
    private javax.swing.JTextField txtBG3;
    private javax.swing.JTextField txtDebeComprobacion1;
    private javax.swing.JTextField txtHaberComprobacion;
    private javax.swing.JTextField txtPasivoBG;
    // End of variables declaration//GEN-END:variables
}
