/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Modelo.Conexion;
import Modelo.Libro;
import Modelo.Plantilla;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio Aranda
 */
public class NuevoLibro extends javax.swing.JFrame {

    /**
     * Creates new form MuestraPlantilla
     */
    public NuevoLibro() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar nuevo libro diario");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa el periodo del libro diario");

        jLabel3.setText("DEL");

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel4.setText("AL");

        jDateChooser2.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        boolean hay = false;
        this.setVisible(false);
        this.dispose();
        Libro l = new Libro();
        l.setCrear(false);

        Conexion c = new Conexion();
        ResultSet rs = c.Consulta("SELECT * FROM `librodiario` ", c.getConexion());

        try {
            while (rs.next()) {
                System.out.println(rs.getString("n_libro"));
                l.setAnterior(Integer.parseInt(rs.getString("n_libro")));
                hay = true;
            }
            rs.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(NuevoLibro.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!hay) {
            System.out.println("cerrando todo");
            System.exit(0);
        }

        Principal p = new Principal();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jDateChooser1.getDate() != null && jDateChooser2.getDate() != null) {
            //primer fecha
            java.util.Date date = jDateChooser1.getDate();

            long d = date.getTime();
            java.sql.Date fecha = new Date(d);
            
            //pasaremos el mes a letras
            String anio = "";
            anio += String.valueOf(fecha).charAt(0);
            anio += String.valueOf(fecha).charAt(1);
            anio += String.valueOf(fecha).charAt(2);
            anio += String.valueOf(fecha).charAt(3);
            String mes = "";
            mes += String.valueOf(fecha).charAt(5);
            mes += String.valueOf(fecha).charAt(6);
            String dia = "";
            dia += String.valueOf(fecha).charAt(8);
            dia += String.valueOf(fecha).charAt(9);
            if(mes.equals("01")){
                mes = "Enero";
            }else if(mes.equals("02")){
                mes = "Febrero";
            }else if(mes.equals("03")){
                mes = "Marzo";
            }else if(mes.equals("04")){
                mes = "Abril";
            }else if(mes.equals("05")){
                mes = "Mayo";
            }else if(mes.equals("06")){
                mes = "Junio";
            }else if(mes.equals("07")){
                mes = "Julio";
            }else if(mes.equals("08")){
                mes = "Agosto";
            }else if(mes.equals("09")){
                mes = "Septiembre";
            }else if(mes.equals("10")){
                mes = "Octubre";
            }else if(mes.equals("11")){
                mes = "Noviembre";
            }else if(mes.equals("12")){
                mes = "Diciembre";
            }
            
             //segunda fecha
            java.util.Date date1 = jDateChooser2.getDate();

            long d1 = date1.getTime();
            java.sql.Date fecha1 = new Date(d1);
            
            //pasaremos el mes a letras
            String anio1 = "";
            anio1 += String.valueOf(fecha1).charAt(0);
            anio1 += String.valueOf(fecha1).charAt(1);
            anio1 += String.valueOf(fecha1).charAt(2);
            anio1 += String.valueOf(fecha1).charAt(3);
            String mes1 = "";
            mes1 += String.valueOf(fecha1).charAt(5);
            mes1 += String.valueOf(fecha1).charAt(6);
            String dia1 = "";
            dia1 += String.valueOf(fecha1).charAt(8);
            dia1 += String.valueOf(fecha1).charAt(9);
            if(mes1.equals("01")){
                mes1 = "Enero";
            }else if(mes1.equals("02")){
                mes1 = "Febrero";
            }else if(mes1.equals("03")){
                mes1 = "Marzo";
            }else if(mes1.equals("04")){
                mes1 = "Abril";
            }else if(mes1.equals("05")){
                mes1 = "Mayo";
            }else if(mes1.equals("06")){
                mes1 = "Junio";
            }else if(mes1.equals("07")){
                mes1 = "Julio";
            }else if(mes1.equals("08")){
                mes1 = "Agosto";
            }else if(mes1.equals("09")){
                mes1 = "Septiembre";
            }else if(mes1.equals("10")){
                mes1 = "Octubre";
            }else if(mes1.equals("11")){
                mes1 = "Noviembre";
            }else if(mes1.equals("12")){
                mes1 = "Diciembre";
            }
            String fechaTotal = "Del " + dia + " de " + mes + " de " + anio + " Al "+ dia1 + " de " + mes1 + " de " + anio1 ;
            
            
             int ultimo = 1;

             Conexion c = new Conexion();
             ResultSet rs = c.Consulta("SELECT n_libro FROM `librodiario` ORDER BY `n_libro` DESC LIMIT 1 ", c.getConexion());
             try {
             if (rs.next()) {
             ultimo = Integer.parseInt(rs.getString("n_libro")) + 1;
             } else {
             ultimo = 1;
             }
             rs.close();
             c.close();
             } catch (SQLException ex) {
             Logger.getLogger(NuevoLibro.class.getName()).log(Level.SEVERE, null, ex);
             }
             c.Ejecutar("INSERT INTO librodiario ( n_libro , Periodo ) values ( '" + (ultimo) + "','" + fechaTotal + "')");
             //cerramos la ventana actual
             this.setVisible(false);
             this.dispose();
             Principal p = new Principal();
             p.setVisible(true);
             p.setLocationRelativeTo(null);
             Libro l = new Libro();
             l.setAnterior(ultimo);
             
        } else {
            JOptionPane.showMessageDialog(null, "LA FECHA NO PUEDE ESTAR VACIA");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoLibro().setVisible(true);
            }
        });
    }

    public String[][] datosTabla(DefaultTableModel table) {
        int nRow = table.getRowCount(), nCol = table.getColumnCount();
        String[][] tableData = new String[nRow][nCol];
        for (int i = 0; i < nRow; i++) {
            for (int j = 0; j < nCol; j++) {
                tableData[i][j] = table.getValueAt(i, j).toString();
                //System.out.println(tableData[i][j]+"("+i+","+j+")");            
            }
        }
        return tableData;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
